import {
  LayoutDashboard,
  CalendarCheck,
  LayoutList,
  Pill,
  Users,
  Stethoscope,
  UserCog,
  CalendarDays,
  ClipboardList,
  FileText,
  CreditCard,
  Package,
  BarChart3,
  ScrollText,
  Settings,
} from 'lucide-react';

export const NAVIGATION_ITEMS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    roleLabels: { doctor: "Today's Schedule", billing: 'Financial Dashboard', receptionist: "Today's Queue", pharmacist: 'Dispensing Queue' },
    icon: LayoutDashboard,
    roleIcons: { doctor: CalendarCheck, receptionist: LayoutList, pharmacist: Pill },
    path: '/dashboard',
    roles: ['admin', 'doctor', 'billing'],
  },
  {
    id: 'patients',
    label: 'Patients',
    roleLabels: { doctor: 'My Patients' },
    icon: Users,
    path: '/patients',
    roles: ['admin', 'doctor', 'receptionist', 'pharmacist'],
  },
  {
    id: 'doctors',
    label: 'Doctors',
    icon: Stethoscope,
    path: '/doctors',
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'staff',
    label: 'Staff',
    icon: UserCog,
    path: '/staff',
    roles: ['admin'],
  },
  {
    id: 'appointments',
    label: 'Appointments',
    icon: CalendarDays,
    path: '/appointments',
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'prescriptions',
    label: 'Prescriptions',
    roleLabels: { pharmacist: 'Prescriptions to Fulfill' },
    icon: ClipboardList,
    path: '/prescriptions',
    roles: ['admin', 'doctor', 'pharmacist'],
  },
  {
    id: 'medical-history',
    label: 'Medical History',
    icon: FileText,
    path: '/medical-history',
    roles: ['admin', 'doctor'],
  },
  {
    id: 'billing',
    label: 'Billing',
    icon: CreditCard,
    path: '/billing',
    roles: ['admin', 'billing'],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: Package,
    path: '/inventory',
    roles: ['admin', 'pharmacist'],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: BarChart3,
    path: '/reports',
    roles: ['admin'],
  },
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    icon: ScrollText,
    path: '/audit-logs',
    roles: ['admin'],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    path: '/settings',
    roles: ['admin', 'doctor', 'receptionist', 'pharmacist', 'billing'],
  },
];
